[app:main]
use = egg:employee_api
sqlalchemy.url = mysql+pymysql://root:tiger@localhost/employee_db5?charset=utf8mb4
jwt.secret = your_super_secret_key
jwt.algorithm = HS256
jwt.expiration_minutes = 5  # Add this line

# Add SQLAlchemy pool settings
sqlalchemy.pool_recycle = 3600
sqlalchemy.pool_pre_ping = true
sqlalchemy.echo = false

[server:main]
use = egg:waitress#main
listen = localhost:6543

[loggers]
keys = root, sqlalchemy

[handlers]
keys = console, file

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console, file

[logger_sqlalchemy]
level = WARN
handlers = 
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_file]
class = logging.handlers.RotatingFileHandler
args = ('employee_api.log', 'a', 1048576, 5)
level = INFO
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s
